name: First workflow

on: push

jobs:
  validar:
    runs-on: ubuntu-latest

    steps:
      - name: Download code
        run: actions/checkout@v5

      - name: Install pytest
        uses: pip install pytest

      - name: Run tests
        run: pytest test.py
